FROM python:3.9-slim-buster

ARG PROJECT_ID

ENV PROJECT_ID=${PROJECT_ID}
ENV PORT=8080

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

CMD exec functions-framework --target=run_pipeline --port=${PORT}
